name: Deploy Worker

on: ["repository_dispatch"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install packages
        run:### Error Analysis:
The logs indicate an **npm error** due pnpm install --frozen-lockfile

      - name: Build Project
 to attempting to read properties of `null`:
- **        run: pnpm build:cloudflare

      - nameError Message:** `Cannot read properties of null (: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken:reading 'matches')`
- **Cause:** This error typically ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wrangler-version: 3.99.0
